<?php

use Illuminate\Database\Seeder;

class CatMatrizIngresosDevenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         {
        DB::table('controlf_catmatrizingresosdeven')->insert([
            
['cri'=>11,'nombrecri'=>'IMPUESTOS SOBRE LOS INGRESOS','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.1','cuentaAb'=>'IMPUESTOS SOBRE LOS INGRESOS'],
['cri'=>11,'nombrecri'=>'IMPUESTOS SOBRE LOS INGRESOS','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.1','cuentaAb'=>'IMPUESTOS SOBRE LOS INGRESOS'],
['cri'=>11,'nombrecri'=>'IMPUESTOS SOBRE LOS INGRESOS','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.1','cuentaAb'=>'IMPUESTOS SOBRE LOS INGRESOS'],
['cri'=>11,'nombrecri'=>'IMPUESTOS SOBRE LOS INGRESOS','caracteristicas'=>'RESOLUCIÓN','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.1','cuentaAb'=>'IMPUESTOS SOBRE LOS INGRESOS'],
['cri'=>12,'nombrecri'=>'IMPUESTOS SOBRE EL PATRIMONIO','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.2','cuentaAb'=>'IMPUESTOS SOBRE EL PATRIMONIO'],
['cri'=>12,'nombrecri'=>'IMPUESTOS SOBRE EL PATRIMONIO','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.2','cuentaAb'=>'IMPUESTOS SOBRE EL PATRIMONIO'],
['cri'=>12,'nombrecri'=>'IMPUESTOS SOBRE EL PATRIMONIO','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.2','cuentaAb'=>'IMPUESTOS SOBRE EL PATRIMONIO'],
['cri'=>12,'nombrecri'=>'IMPUESTOS SOBRE EL PATRIMONIO','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.2','cuentaAb'=>'IMPUESTOS SOBRE EL PATRIMONIO'],
['cri'=>13,'nombrecri'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.3','cuentaAb'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES'],
['cri'=>13,'nombrecri'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.3','cuentaAb'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES'],
['cri'=>13,'nombrecri'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.3','cuentaAb'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES'],
['cri'=>13,'nombrecri'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.3','cuentaAb'=>'IMPUESTOS SOBRE LA PRODUCCIÓN, EL CONSUMO Y LAS TRANSACCIONES'],
['cri'=>14,'nombrecri'=>'IMPUESTOS AL COMERCIO EXTERIOR	','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.4','cuentaAb'=>'IMPUESTOS AL COMERCIO EXTERIOR'],
['cri'=>14,'nombrecri'=>'IMPUESTOS AL COMERCIO EXTERIOR	','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.4','cuentaAb'=>'IMPUESTOS AL COMERCIO EXTERIOR'],
['cri'=>14,'nombrecri'=>'IMPUESTOS AL COMERCIO EXTERIOR	','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'4.1.1.4','cuentaAb'=>'IMPUESTOS AL COMERCIO EXTERIOR'],
['cri'=>14,'nombrecri'=>'IMPUESTOS AL COMERCIO EXTERIOR	','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.4','cuentaAb'=>'IMPUESTOS AL COMERCIO EXTERIOR'],
['cri'=>15,'nombrecri'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'	4.1.1.5		','cuentaAb'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES'],
['cri'=>15,'nombrecri'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.5','cuentaAb'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES'],
['cri'=>15,'nombrecri'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.5','cuentaAb'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES'],
['cri'=>15,'nombrecri'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.5','cuentaAb'=>'IMPUESTOS SOBRE NÓMINAS Y ASIMILABLES'],
['cri'=>16,'nombrecri'=>'IMPUESTOS ECOLÓGICOS','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.6','cuentaAb'=>'IMPUESTOS ECOLÓGICOS'],
['cri'=>16,'nombrecri'=>'IMPUESTOS ECOLÓGICOS','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.6','cuentaAb'=>'IMPUESTOS ECOLÓGICOS'],
['cri'=>16,'nombrecri'=>'IMPUESTOS ECOLÓGICOS','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'4.1.1.6','cuentaAb'=>'IMPUESTOS ECOLÓGICOS'],
['cri'=>16,'nombrecri'=>'IMPUESTOS ECOLÓGICOS','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'1.1.2.4','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.6','cuentaAb'=>'IMPUESTOS ECOLÓGICOS'],
['cri'=>17,'nombrecri'=>'ACCESORIOS','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.7','cuentaAb'=>'ACCESORIOS DE IMPUESTOS'],
['cri'=>17,'nombrecri'=>'ACCESORIOS','caracteristicas'=>'CONVENIO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.7','cuentaAb'=>'ACCESORIOS DE IMPUESTOS'],
['cri'=>17,'nombrecri'=>'ACCESORIOS','caracteristicas'=>'PAGO EXTEMPORÁNEO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'4.1.1.7','cuentaAb'=>'ACCESORIOS DE IMPUESTOS'],
['cri'=>17,'nombrecri'=>'ACCESORIOS','caracteristicas'=>'RESOLUCIÓN JUDICIAL CP','cargo'=>'	1.1.2.4	','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'4.1.1.7','cuentaAb'=>'ACCESORIOS DE IMPUESTOS'],
['cri'=>18,'nombrecri'=>'OTROS IMPUESTOS','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.9','cuentaAb'=>'OTROS IMPUESTOS'],
['cri'=>18,'nombrecri'=>'OTROS IMPUESTOS','caracteristicas'=>'	CONVENIO		','cargo'=>'	1.1.2.4	','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.9','cuentaAb'=>'OTROS IMPUESTOS'],
['cri'=>18,'nombrecri'=>'OTROS IMPUESTOS','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.9','cuentaAb'=>'OTROS IMPUESTOS'],
['cri'=>18,'nombrecri'=>'OTROS IMPUESTOS','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.1.9','cuentaAb'=>'OTROS IMPUESTOS'],
['cri'=>19,'nombrecri'=>'IMPUESTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS	','caracteristicas'=>'PAGO EN TÉRMINO','cargo'=>'1.1.2.4','cuentaC'=>'INGRESOS POR RECUPERAR A CORTO PLAZO','abono'=>'4.1.9.1','cuentaAb'=>'IMPUESTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS'],
['cri'=>null,'nombrecri'=>'	FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'			','cargo'=>'','cuentaC'=>'','abono'=>'','cuentaAb'=>'	"Causados en Ejercicios Fiscales
Anteriores Pendientes de Liquidación o Pago"		'],
['cri'=>	19	,'nombrecri'=>'	IMPUESTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.1		','cuentaAb'=>'	"Impuestos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación
o Pago"		'],
['cri'=>	19	,'nombrecri'=>'	IMPUESTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.1		','cuentaAb'=>'	"Impuestos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación
o Pago"		'],
['cri'=>	19	,'nombrecri'=>'	IMPUESTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.1		','cuentaAb'=>'	"Impuestos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación
o Pago"		'],
['cri'=>	21	,'nombrecri'=>'	APORTACIONES PARA FONDOS DE VIVIENDA	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.1		','cuentaAb'=>'	Aportaciones para Fondos de Vivienda		'],
['cri'=>	21	,'nombrecri'=>'	APORTACIONES PARA FONDOS DE VIVIENDA	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.1		','cuentaAb'=>'	Aportaciones para Fondos de Vivienda		'],
['cri'=>	21	,'nombrecri'=>'	APORTACIONES PARA FONDOS DE VIVIENDA	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.1		','cuentaAb'=>'	Aportaciones para Fondos de Vivienda		'],
['cri'=>	21	,'nombrecri'=>'	APORTACIONES PARA FONDOS DE VIVIENDA	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.1		','cuentaAb'=>'	Aportaciones para Fondos de Vivienda		'],
['cri'=>	22	,'nombrecri'=>'	CUOTAS PARA EL SEGURO SOCIAL	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.2		','cuentaAb'=>'	Cuotas para el Seguro Social		'],
['cri'=>	22	,'nombrecri'=>'	CUOTAS PARA EL SEGURO SOCIAL	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.2		','cuentaAb'=>'	Cuotas para el Seguro Social		'],
['cri'=>	22	,'nombrecri'=>'	CUOTAS PARA EL SEGURO SOCIAL	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.2		','cuentaAb'=>'	Cuotas para el Seguro Social		'],
['cri'=>	22	,'nombrecri'=>'	CUOTAS PARA EL SEGURO SOCIAL	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.2		','cuentaAb'=>'	Cuotas para el Seguro Social		'],
['cri'=>	23	,'nombrecri'=>'	CUOTAS DE AHORRO PARA EL RETIRO	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.3		','cuentaAb'=>'	Cuotas de Ahorro para el Retiro		'],
['cri'=>	23	,'nombrecri'=>'	CUOTAS DE AHORRO PARA EL RETIRO	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.3		','cuentaAb'=>'	Cuotas de Ahorro para el Retiro		'],
['cri'=>	23	,'nombrecri'=>'	CUOTAS DE AHORRO PARA EL RETIRO	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.3		','cuentaAb'=>'	Cuotas de Ahorro para el Retiro		'],
['cri'=>	23	,'nombrecri'=>'	CUOTAS DE AHORRO PARA EL RETIRO	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.3		','cuentaAb'=>'	Cuotas de Ahorro para el Retiro		'],
['cri'=>	24	,'nombrecri'=>'	OTRAS CUOTAS Y APORTACIONES PARA LA SEGURIDAD SOCIAL	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.9		','cuentaAb'=>'	Otras Cuotas y Aportaciones para la Seguridad Social		'],
['cri'=>	24	,'nombrecri'=>'	OTRAS CUOTAS Y APORTACIONES PARA LA SEGURIDAD SOCIAL	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.9		','cuentaAb'=>'	Otras Cuotas y Aportaciones para la Seguridad Social		'],
['cri'=>	24	,'nombrecri'=>'	OTRAS CUOTAS Y APORTACIONES PARA LA SEGURIDAD SOCIAL	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.9		','cuentaAb'=>'	Otras Cuotas y Aportaciones para la Seguridad Social		'],
['cri'=>	24	,'nombrecri'=>'	OTRAS CUOTAS Y APORTACIONES PARA LA SEGURIDAD SOCIAL	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.9		','cuentaAb'=>'	Otras Cuotas y Aportaciones para la Seguridad Social		'],
['cri'=>	25	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.4		','cuentaAb'=>'	Accesorios de Cuotas y Aportaciones de Seguridad Social		'],
['cri'=>	25	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.4		','cuentaAb'=>'	Accesorios de Cuotas y Aportaciones de Seguridad Social		'],
['cri'=>	25	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.4		','cuentaAb'=>'	Accesorios de Cuotas y Aportaciones de Seguridad Social		'],
['cri'=>	25	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.2.4		','cuentaAb'=>'	Accesorios de Cuotas y Aportaciones de Seguridad Social		'],
['cri'=>	31	,'nombrecri'=>'	CONTRIBUCIONES DE MEJORAS POR OBRAS PÚBLICAS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.3.1		','cuentaAb'=>'	Contribuciones de Mejoras por Obras Públicas		'],
['cri'=>	39	,'nombrecri'=>'	CONTRIBUCIONES DE MEJORAS NO COMPRENDIDAS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	"Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de
liquidación o pago"		'],
['cri'=>	41	,'nombrecri'=>'	DERECHOS POR EL USO, GOCE, APROVECHAMIENTO O EXPLOTACIÓN DE BIENES DE DOMINIO PÚBLICO	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.1		','cuentaAb'=>'	"Derechos por el uso, goce, aprovechamiento o explotación de
bienes de dominio público"		'],
['cri'=>	41	,'nombrecri'=>'	DERECHOS POR EL USO, GOCE, APROVECHAMIENTO O EXPLOTACIÓN DE BIENES DE DOMINIO PÚBLICO	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.1		','cuentaAb'=>'	"Derechos por el uso, goce,
aprovechamiento o explotación de bienes de dominio público"		'],
['cri'=>	41	,'nombrecri'=>'	DERECHOS POR EL USO, GOCE, APROVECHAMIENTO O EXPLOTACIÓN DE BIENES DE DOMINIO PÚBLICO	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.1		','cuentaAb'=>'	"Derechos por el uso, goce,
aprovechamiento o explotación de bienes de dominio público"		'],
['cri'=>	41	,'nombrecri'=>'	DERECHOS POR EL USO, GOCE, APROVECHAMIENTO O EXPLOTACIÓN DE BIENES DE DOMINIO PÚBLICO	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.1		','cuentaAb'=>'	"Derechos por el uso, goce, aprovechamiento o explotación de
bienes de dominio público"		'],
['cri'=>	42	,'nombrecri'=>'	DERECHOS A LOS HIDROCARBUROS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.2		','cuentaAb'=>'	Derechos a los hidrocarburos		'],
['cri'=>	42	,'nombrecri'=>'	DERECHOS A LOS HIDROCARBUROS	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.2		','cuentaAb'=>'	Derechos a los hidrocarburos		'],
['cri'=>	42	,'nombrecri'=>'	DERECHOS A LOS HIDROCARBUROS	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.2		','cuentaAb'=>'	Derechos a los hidrocarburos		'],
['cri'=>	42	,'nombrecri'=>'	DERECHOS A LOS HIDROCARBUROS	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.2		','cuentaAb'=>'	Derechos a los hidrocarburos		'],
['cri'=>	43	,'nombrecri'=>'	DERECHOS POR PRESTACIÓN DE SERVICIOS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.3		','cuentaAb'=>'	Derechos por prestación de servicios		'],
['cri'=>	43	,'nombrecri'=>'	DERECHOS POR PRESTACIÓN DE SERVICIOS	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.3		','cuentaAb'=>'	Derechos por prestación de servicios		'],
['cri'=>	43	,'nombrecri'=>'	DERECHOS POR PRESTACIÓN DE SERVICIOS	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.3		','cuentaAb'=>'	Derechos por prestación de servicios		'],
['cri'=>	43	,'nombrecri'=>'	DERECHOS POR PRESTACIÓN DE SERVICIOS	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.3		','cuentaAb'=>'	Derechos por prestación de servicios		'],
['cri'=>	44	,'nombrecri'=>'	OTROS DERECHOS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.9		','cuentaAb'=>'	Otros Derechos		'],
['cri'=>	44	,'nombrecri'=>'	OTROS DERECHOS	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.9		','cuentaAb'=>'	Otros Derechos		'],
['cri'=>	44	,'nombrecri'=>'	OTROS DERECHOS	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.9		','cuentaAb'=>'	Otros Derechos		'],
['cri'=>	44	,'nombrecri'=>'	OTROS DERECHOS	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.9		','cuentaAb'=>'	Otros Derechos		'],
['cri'=>	45	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.4		','cuentaAb'=>'	Accesorios de Derechos		'],
['cri'=>	45	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.4		','cuentaAb'=>'	Accesorios de Derechos		'],
['cri'=>	45	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.4		','cuentaAb'=>'	Accesorios de Derechos		'],
['cri'=>	45	,'nombrecri'=>'	ACCESORIOS	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.4.4		','cuentaAb'=>'	Accesorios de Derechos		'],
['cri'=>	49	,'nombrecri'=>'	DERECHOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Pago en término		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de liquidación o pago		'],
['cri'=>	49	,'nombrecri'=>'	DERECHOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Convenio		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	"Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de
liquidación o pago"		'],
['cri'=>	49	,'nombrecri'=>'	DERECHOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Pago extemporáneo		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	"Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de
liquidación o pago"		'],
['cri'=>	49	,'nombrecri'=>'	DERECHOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'	Resolución judicial CP		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de liquidación o pago		'],
['cri'=>	51	,'nombrecri'=>'	PRODUCTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.5.1		','cuentaAb'=>'	Productos derivados del uso y aprovechamiento de bienes no sujetos a régimen de dominio público		'],
['cri'=>	51	,'nombrecri'=>'	PRODUCTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.5.2		','cuentaAb'=>'	Enajenación de bienes muebles no sujetos a ser inventariados		'],
['cri'=>	51	,'nombrecri'=>'	PRODUCTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.5.9		','cuentaAb'=>'	Otros productos que generan ingresos corrientes		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.3.1.		','cuentaAb'=>'	Terrenos		'],
['cri'=>	null,'nombrecri'=>'		','caracteristicas'=>'	apertura CRI		','cargo'=>'		','cuentaC'=>'		','abono'=>'			','cuentaAb'=>'			'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.3.2		','cuentaAb'=>'	Viviendas		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.3.3		','cuentaAb'=>'	Edificios no Residenciales		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.3.9		','cuentaAb'=>'	Otros bienes Inmuebles		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.1		','cuentaAb'=>'	Mobiliario y Equipo de Administración		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.2		','cuentaAb'=>'	Mobiliario y Equipo Educacional y Recreativo		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.3		','cuentaAb'=>'	Equipo e Instrumental Médico y de Laboratorio		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.4		','cuentaAb'=>'	Equipo de Transporte		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.5		','cuentaAb'=>'	Equipo de Defensa y Seguridad		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.6		','cuentaAb'=>'	Maquinaria, Otros Equipos y Herramientas		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.7		','cuentaAb'=>'	Colecciones, Obras de Arte y Objetos Valiosos		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.4.8		','cuentaAb'=>'	Activos Biológicos		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.5.1		','cuentaAb'=>'	Software		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.5.2		','cuentaAb'=>'	Patentes, Marcas y Derechos		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.5.3		','cuentaAb'=>'	Concesiones y Franquicias		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.5.4		','cuentaAb'=>'	Licencias		'],
['cri'=>	52	,'nombrecri'=>'	PRODUCTOS DE CAPITAL	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	1.2.5.9		','cuentaAb'=>'	Otros Activos Intangibles		'],
['cri'=>	59	,'nombrecri'=>'	PRODUCTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'			','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	"Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de
liquidación o pago"		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.1		','cuentaAb'=>'	Incentivos derivados de la Colaboración Fiscal		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.2		','cuentaAb'=>'	Multas		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.3		','cuentaAb'=>'	Indemnizaciones		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.4		','cuentaAb'=>'	Reintegros		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.5		','cuentaAb'=>'	Aprovechamientos provenientes de obras públicas		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.6		','cuentaAb'=>'	Aprovechamientos por Participaciones derivadas de la		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.7		','cuentaAb'=>'	Aprovechamientos por Aportaciones		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.8		','cuentaAb'=>'	Aprovechamientos por Cooperaciones		'],
['cri'=>	61	,'nombrecri'=>'	APROVECHAMIENTOS DE TIPO CORRIENTE	','caracteristicas'=>'	Requiere apertura CRI		','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.6.9		','cuentaAb'=>'	Otros Aprovechamientos		'],
['cri'=>	69	,'nombrecri'=>'	APROVECHAMIENTOS NO COMPRENDIDOS EN LAS FRACCIONES DE LA LEY DE INGRESOS CAUSADAS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN O PAGO	','caracteristicas'=>'			','cargo'=>'	1.1.2.4	','cuentaC'=>'	INGRESOS POR RECUPERAR A CORTO PLAZO	','abono'=>'	4.1.9.2		','cuentaAb'=>'	"Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no comprendidos en las Fracciones de la ley de Ingresos Causados en ejercicios Fiscales anteriores pendientes de
liquidación o pago"		'],
['cri'=>	71	,'nombrecri'=>'	INGRESOS POR VENTAS DE BIENES Y SERVICIOS DE ORGANISMOS DESCENTRALIZADOS	','caracteristicas'=>'			','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	4.1.7.3		','cuentaAb'=>'	Ingresos por venta de bienes y servicios de organismos descentralizados		'],
['cri'=>	72	,'nombrecri'=>'	INGRESOS DE OPERACIÓN DE ENTIDADES PARAESTATALES EMPRESARIALES	','caracteristicas'=>'			','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	4.1.7.4		','cuentaAb'=>'	"Ingresos de operación de Entidades Paraestatales empresariales y no
financieras"		'],
['cri'=>	73	,'nombrecri'=>'	INGRESOS POR VENTAS DE BIENES Y SERVICIOS PRODUCIDOS EN ESTABLECIMIENTOS DEL GOBIERNO CENTRAL	','caracteristicas'=>'			','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	4.1.7.2		','cuentaAb'=>'	Ingresos por venta de bienes y servicios producidos en establecimientos del gobierno		'],
['cri'=>	82	,'nombrecri'=>'	APORTACIONES	','caracteristicas'=>'	S/Origen		','cargo'=>'	1.1.2.2	','cuentaC'=>'	CUENTAS POR COBRAR A CORTO PLAZO	','abono'=>'	4.2.1.2		','cuentaAb'=>'	Aportaciones		'],
['cri'=>83,'nombrecri'=>'CONVENIOS','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.1.3','cuentaAb'=>'CONVENIOS'],
['cri'=>81,'nombrecri'=>'PARTICIPACIONES','CARACTERISTICAS'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.1.1','cuentaAb'=>'participaciones'],
['cri'=>91,'nombrecri'=>'TRANSFERENCIAS INTERNAS Y ASIGNACIONES AL SECTOR PÚBLICO','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.2.1','cuentaAb'=>'transferencias internas y asignaciones al sector público'],
['cri'=>92,'nombrecri'=>'TRANSFERENCIAS AL RESTO DEL SECTOR PÚBLICO','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.2.2','cuentaAb'=>'transferencias al resto del sector público'],
['cri'=>93,'nombrecri'=>'SUBSIDIOS Y SUBVENCIONES','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.2.3','cuentaAb'=>'subsidios y subvenciones'],
['cri'=>94,'nombrecri'=>'AYUDAS SOCIALES','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.2.4','cuentaAb'=>'ayudas sociales'],
['cri'=>83,'nombrecri'=>'PENSIONES Y JUBILACIONES','caracteristicas'=>'S/Origen','cargo'=>'1.1.2.2','cuentaC'=>'CUENTAS POR COBRAR A CORTO PLAZO', 'abono'=>'4.2.2.','cuentaAb'=>'PENSIONES Y JUBILACIONES'],


            
        ]);
    }
    
}


}  

