<?php

use Illuminate\Database\Seeder;

class CatObjetoGastoSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */


  public function run()
  {
   DB::table('cat_objeto_gasto')->insert([
     ['id'=>'','codigo_obgasto' =>	10000000	, 'nombre_obgasto' => 'SERVICIOS PERSONALES', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	11000000	, 'nombre_obgasto' => 'REMUNERACIONES AL PERSONAL DE CARÁCTER PERMANENTE', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	11300000	, 'nombre_obgasto' => 'SUELDOS BASE AL PERSONAL PERMANENTE', 'obgasto_padre' => 	2, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	11300001	, 'nombre_obgasto' => 'SUELDOS Y SALARIOS', 'obgasto_padre' => 	3, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	11300002	, 'nombre_obgasto' => 'SOBRESUELDO JERARQUIZACIÓN TERCIARIA POLICIAL', 'obgasto_padre' => 	3, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12000000	, 'nombre_obgasto' => 'REMUNERACIONES AL PERSONAL DE CARÁCTER TRANSITORIO', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12100000	, 'nombre_obgasto' => 'HONORARIOS ASIMILABLES A SALARIOS', 'obgasto_padre' => 	6, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12100002	, 'nombre_obgasto' => 'HONORARIOS PROFESIONALES', 'obgasto_padre' => 	7, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12200000	, 'nombre_obgasto' => 'SUELDOS BASE AL PERSONAL EVENTUAL', 'obgasto_padre' => 	6, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12200001	, 'nombre_obgasto' => 'SUELDOS AL PERSONAL EVENTUAL', 'obgasto_padre' => 	9, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12200003	, 'nombre_obgasto' => 'SUELDOS AL EMPLEADO TEMPORAL ADMINISTRATIVO', 'obgasto_padre' => 	9, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12300000	, 'nombre_obgasto' => 'RETRIBUCIONES POR SERVICIOS DE CARÁCTER SOCIAL', 'obgasto_padre' => 	6, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	12300002	, 'nombre_obgasto' => 'AYUDA POR SERVICIOS', 'obgasto_padre' => 	12, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13000000	, 'nombre_obgasto' => 'REMUNERACIONES ADICIONALES Y ESPECIALES', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13100000	, 'nombre_obgasto' => 'PRIMAS POR AÑOS DE SERVICIOS EFECTIVOS PRESTADOS', 'obgasto_padre' => 	14, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13100001	, 'nombre_obgasto' => 'QUINQUENIOS', 'obgasto_padre' => 	15, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13100002	, 'nombre_obgasto' => 'QUINQUENIOS NUEVA GENERACIÓN', 'obgasto_padre' => 	15, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13200000	, 'nombre_obgasto' => 'PRIMAS DE VACACIONES, DOMINICAL Y GRATIFICACIÓN DE FIN DE AÑO', 'obgasto_padre' => 	14, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13200002	, 'nombre_obgasto' => 'GRATIFICACIÓN ANUAL', 'obgasto_padre' => 	18, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13200003	, 'nombre_obgasto' => 'PRIMA VACACIONAL', 'obgasto_padre' => 	18, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13200004	, 'nombre_obgasto' => 'BONO ANUAL DE DESPENSA', 'obgasto_padre' => 	18, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13200005	, 'nombre_obgasto' => 'CANASTA NAVIDEÑA', 'obgasto_padre' => 	18, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13300000	, 'nombre_obgasto' => 'HORAS EXTRAORDINARIAS', 'obgasto_padre' => 	14, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13300001	, 'nombre_obgasto' => 'COMPENSACIÓN POR SERVICIOS DE TURNO VESPERTINO', 'obgasto_padre' => 	23, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13400000	, 'nombre_obgasto' => 'COMPENSACIONES', 'obgasto_padre' => 	14, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13400005	, 'nombre_obgasto' => 'COMPENSACIÓN POR AJUSTE DE CALENDARIO', 'obgasto_padre' => 	25, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	13400007	, 'nombre_obgasto' => 'COMPENSACIÓN ADMINISTRATIVA', 'obgasto_padre' => 	25, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14000000	, 'nombre_obgasto' => 'SEGURIDAD SOCIAL', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14100000	, 'nombre_obgasto' => 'APORTACIONES DE SEGURIDAD SOCIAL', 'obgasto_padre' => 	28, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14100001	, 'nombre_obgasto' => 'INSTITUTO MEXICANO DEL SEGURO SOCIAL', 'obgasto_padre' => 	29, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14100002	, 'nombre_obgasto' => 'SEGURO INSTITUCIONAL', 'obgasto_padre' => 	29, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14100004	, 'nombre_obgasto' => 'SEGURO DE VIDA Y PAGO DE MARCHA', 'obgasto_padre' => 	29, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14300000	, 'nombre_obgasto' => 'APORTACIONES AL SISTEMA PARA EL RETIRO', 'obgasto_padre' => 	28, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14300001	, 'nombre_obgasto' => 'SISTEMA DE AHORRO PARA EL RETIRO', 'obgasto_padre' => 	33, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	14300002	, 'nombre_obgasto' => 'SEGURO DE RETIRO', 'obgasto_padre' => 	33, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15000000	, 'nombre_obgasto' => 'OTRAS PRESTACIONES SOCIALES Y ECONÓMICAS', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15200000	, 'nombre_obgasto' => 'INDEMNIZACIONES', 'obgasto_padre' => 	36, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15200001	, 'nombre_obgasto' => 'PENSIONES, JUBILACIONES E INDEMNIZACIONES Y HABERES DE RETIRO', 'obgasto_padre' => 	37, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15300000	, 'nombre_obgasto' => 'PRESTACIONES Y HABERES DE RETIRO', 'obgasto_padre' => 	36, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15300001	, 'nombre_obgasto' => 'LIQUIDACIONES POR INDEMNIZACIONES Y POR SUELDOS Y SALARIOS CAÍDOS CONTRACTUALES', 'obgasto_padre' => 	39, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400000	, 'nombre_obgasto' => 'PRESTACIONES CONTRACTUALES', 'obgasto_padre' => 	36, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400001	, 'nombre_obgasto' => 'AYUDA PARA PASAJES', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400002	, 'nombre_obgasto' => 'AYUDA PARA LENTES Y APARATOS ORTOPÉDICOS', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400004	, 'nombre_obgasto' => 'DESPENSA', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400005	, 'nombre_obgasto' => 'PREVISIÓN SOCIAL MÚLTIPLE', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400007	, 'nombre_obgasto' => 'PAGO DE DÍAS ECONÓMICOS NO DISFRUTADOS', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400014	, 'nombre_obgasto' => 'AYUDA PARA LA ADQUISICIÓN DE ÚTILES ESCOLARES', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400017	, 'nombre_obgasto' => 'PAGO DEL DÍA DE LAS MADRES', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400023	, 'nombre_obgasto' => 'COMPENSACIÓN TEMPORAL COMPACTABLE', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400025	, 'nombre_obgasto' => 'ASIGNACIÓN POR ACTIVIDADES CULTURALES', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400026	, 'nombre_obgasto' => 'PREVISIÓN PARA POLICÍAS', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400029	, 'nombre_obgasto' => 'AYUDADEPREVISIÓNSOCIALPOR RIESGODE SEGURIDAD PÚBLICA', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400030	, 'nombre_obgasto' => 'GRATIFICACIÓN EXTRAORDINARIA', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400031	, 'nombre_obgasto' => 'GRATIFICACIÓN', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15400032	, 'nombre_obgasto' => 'COMPENSACIÓN POR SERVICIOS ESPECIALES', 'obgasto_padre' => 	41, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15500000	, 'nombre_obgasto' => 'APOYOS A LA CAPACITACIÓN DE LOS SERVIDORES PÚBLICOS', 'obgasto_padre' => 	36, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	15500002	, 'nombre_obgasto' => 'AYUDA PARA CAPACITACIÓN Y DESARROLLO', 'obgasto_padre' => 	56, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	17000000	, 'nombre_obgasto' => 'PAGO DE ESTÍMULOS A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	1, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	17100000	, 'nombre_obgasto' => 'ESTÍMULOS', 'obgasto_padre' => 	58, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	17100001	, 'nombre_obgasto' => 'ESTÍMULO POR ANTIGÜEDAD', 'obgasto_padre' => 	59, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	17100006	, 'nombre_obgasto' => 'ESTÍMULO A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	59, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	17100010	, 'nombre_obgasto' => 'ESTÍMULO AL DESTACADO DESEMPEÑO', 'obgasto_padre' => 	59, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	20000000	, 'nombre_obgasto' => 'MATERIALES Y SUMINISTROS', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21000000	, 'nombre_obgasto' => 'MATERIALES DE ADMINISTRACIÓN, EMISIÓN DE DOCUMENTOS Y ARTÍCULOS OFICIALES', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21100000	, 'nombre_obgasto' => 'MATERIALES, ÚTILES Y EQUIPOS MENORES DE OFICINA', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21100001	, 'nombre_obgasto' => 'MATERIALES Y ÚTILES DE OFICINA', 'obgasto_padre' => 	65, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21200000	, 'nombre_obgasto' => 'MATERIALES Y ÚTILES DE IMPRESIÓN Y REPRODUCCIÓN', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21200001	, 'nombre_obgasto' => 'MATERIALES Y ÚTILES DE IMPRESIÓN Y REPRODUCCIÓN', 'obgasto_padre' => 	67, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21200002	, 'nombre_obgasto' => 'MATERIAL DE FOTOGRAFÍA', 'obgasto_padre' => 	67, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21400000	, 'nombre_obgasto' => 'MATERIALES, ÚTILES Y EQUIPOS MENORES DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21400001	, 'nombre_obgasto' => 'MATERIALES Y ÚTILES PARA EL PROCESAMIENTO EN EQUIPOS Y BIENES INFORMÁTICOS', 'obgasto_padre' => 	70, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21500000	, 'nombre_obgasto' => 'MATERIAL IMPRESO E INFORMACIÓN DIGITAL', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21500001	, 'nombre_obgasto' => 'MATERIAL PARA INFORMACIÓN', 'obgasto_padre' => 	72, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21500002	, 'nombre_obgasto' => 'SUSCRIPCIÓN A PERIÓDICOS Y MEDIOS INFORMATIVOS', 'obgasto_padre' => 	72, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21500003	, 'nombre_obgasto' => 'MATERIAL DE CINEMATOGRAFÍA Y AUDIOVISUAL', 'obgasto_padre' => 	72, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21600000	, 'nombre_obgasto' => 'MATERIAL DE LIMPIEZA', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21600001	, 'nombre_obgasto' => 'MATERIAL DE LIMPIEZA', 'obgasto_padre' => 	76, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21700000	, 'nombre_obgasto' => 'MATERIALES Y ÚTILES DE ENSEÑANZA', 'obgasto_padre' => 	64, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	21700001	, 'nombre_obgasto' => 'MATERIAL DIDÁCTICO', 'obgasto_padre' => 	78, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22000000	, 'nombre_obgasto' => 'ALIMENTOS Y UTENSILIOS', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22100000	, 'nombre_obgasto' => 'PRODUCTOS ALIMENTICIOS PARA PERSONAS', 'obgasto_padre' => 	80, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22100001	, 'nombre_obgasto' => 'PRODUCTOS ALIMENTICIOS PARA LOS EFECTIVOS QUE PARTICIPEN EN PROGRAMAS DE SEGURIDAD PÚBLICA (ACADEMIA DE POLICÍA COCINAS MÓVILES)', 'obgasto_padre' => 	81, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22100002	, 'nombre_obgasto' => 'PRODUCTOS ALIMENTICIOS PARA PERSONAS DERIVADO DE LA PRESTACIÓN DE SERVICIOS PÚBLICOS EN UNIDADES DE SALUD, EDUCATIVAS DE READAPTACIÓN SOCIAL Y OTRAS', 'obgasto_padre' => 	81, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22100004	, 'nombre_obgasto' => 'PRODUCTOSALIMENTICIOSPARAELPERSONAL DERIVADO DE ACTIVIDADES EXTRAORDINARIAS', 'obgasto_padre' => 	81, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22100005	, 'nombre_obgasto' => 'AGUA PURIFICADA', 'obgasto_padre' => 	81, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22300000	, 'nombre_obgasto' => 'UTENSILIOS PARA EL SERVICIO DE ALIMENTACIÓN', 'obgasto_padre' => 	80, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	22300001	, 'nombre_obgasto' => 'UTENSILIOS PARA SERVICIO DE ALIMENTACIÓN', 'obgasto_padre' => 	86, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24000000	, 'nombre_obgasto' => 'MATERIALES Y ARTÍCULOS DE CONSTRUCCIÓN Y DE REPARACIÓN', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24100000	, 'nombre_obgasto' => 'PRODUCTOS MINERALES NO METÁLICOS', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24100001	, 'nombre_obgasto' => 'PRODUCTOS MINERALES NO METÁLICOS', 'obgasto_padre' => 	89, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24200000	, 'nombre_obgasto' => 'CEMENTO Y PRODUCTOS DE CONCRETO', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24200001	, 'nombre_obgasto' => 'CEMENTO Y PRODUCTOS DE CONCRETO', 'obgasto_padre' => 	91, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24300000	, 'nombre_obgasto' => 'CAL YESO Y PRODUCTOS DE YESO', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24300001	, 'nombre_obgasto' => 'CAL YESO Y PRODUCTOS DE YESO', 'obgasto_padre' => 	93, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24400000	, 'nombre_obgasto' => 'MADERA Y PRODUCTOS DE MADERA', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24400001	, 'nombre_obgasto' => 'MADERA Y PRODUCTOS DE MADERA', 'obgasto_padre' => 	95, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24500000	, 'nombre_obgasto' => 'VIDRIO Y PRODUCTOS DE VIDRIO', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24500001	, 'nombre_obgasto' => 'VIDRIO Y PRODUCTOS DE VIDRIO', 'obgasto_padre' => 	97, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24600000	, 'nombre_obgasto' => 'MATERIAL ELÉCTRICO Y ELECTRÓNICO', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24600001	, 'nombre_obgasto' => 'MATERIAL ELÉCTRICO Y ELECTRÓNICO', 'obgasto_padre' => 	99, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24700000	, 'nombre_obgasto' => 'ARTÍCULOS METÁLICOS PARA LA CONSTRUCCIÓN', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24700001	, 'nombre_obgasto' => 'ARTÍCULOS METÁLICOS PARA LA CONSTRUCCIÓN', 'obgasto_padre' => 	101, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24800000	, 'nombre_obgasto' => 'MATERIALES COMPLEMENTARIOS', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24800001	, 'nombre_obgasto' => 'PLANTAS DE ORNATO', 'obgasto_padre' => 	103, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24900000	, 'nombre_obgasto' => 'OTROSMATERIALESYARTÍCULOSDECONSTRUCCIÓNY REPARACIÓN', 'obgasto_padre' => 	88, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	24900001	, 'nombre_obgasto' => 'PINTURAS', 'obgasto_padre' => 	105, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25000000	, 'nombre_obgasto' => 'PRODUCTOS QUÍMICOS, FARMACÉUTICOS Y DE LABORATORIO', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25100000	, 'nombre_obgasto' => 'PRODUCTOS QUÍMICOS BÁSICOS', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25100001	, 'nombre_obgasto' => 'SUSTANCIAS QUÍMICAS', 'obgasto_padre' => 	108, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25200000	, 'nombre_obgasto' => 'FERTILIZANTES, PESTICIDAS Y OTROS AGROQUÍMICOS', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25200001	, 'nombre_obgasto' => 'PLAGUICIDAS, ABONOS Y FERTILIZANTES', 'obgasto_padre' => 	110, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25300000	, 'nombre_obgasto' => 'MEDICINAS Y PRODUCTOS FARMACÉUTICOS', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25300001	, 'nombre_obgasto' => 'MEDICINAS Y PRODUCTOS FARMACÉUTICOS', 'obgasto_padre' => 	112, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25400000	, 'nombre_obgasto' => 'MATERIALES, ACCESORIOS Y SUMINISTROS MÉDICOS', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25400001	, 'nombre_obgasto' => 'MATERIALES, ACCESORIOS Y SUMINISTROS MÉDICOS', 'obgasto_padre' => 	114, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25500000	, 'nombre_obgasto' => 'MATERIALES, ACCESORIOS Y SUMINISTROS DE LABORATORIO', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25500001	, 'nombre_obgasto' => 'MATERIALES, ACCESORIOSYSUMINISTROSDE LABORATORIO', 'obgasto_padre' => 	116, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	25600000	, 'nombre_obgasto' => 'FIBRAS SINTÉTICAS, HULES, PLÁSTICO Y DERIVADOS', 'obgasto_padre' => 	107, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	26000000	, 'nombre_obgasto' => 'COMBUSTIBLES, LUBRICANTES Y ADITIVOS', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	26100000	, 'nombre_obgasto' => 'COMBUSTIBLES, LUBRICANTES Y ADITIVOS', 'obgasto_padre' => 	119, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	26100002	, 'nombre_obgasto' => 'COMBUSTIBLES, LUBRICANTESYADITIVOSPARA SERVICIOS Y OPERACIÓN DE PROGRAMAS PÚBLICOS', 'obgasto_padre' => 	120, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27000000	, 'nombre_obgasto' => 'VESTUARIO, BLANCOS, PRENDAS DE PROTECCIÓN Y ARTÍCULOS DEPORTIVOS', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27100000	, 'nombre_obgasto' => 'VESTUARIOS Y UNIFORMES', 'obgasto_padre' => 	122, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27100001	, 'nombre_obgasto' => 'VESTUARIO Y UNIFORMES', 'obgasto_padre' => 	123, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27200000	, 'nombre_obgasto' => 'PRENDAS DE SEGURIDAD Y PROTECCIÓN PERSONAL', 'obgasto_padre' => 	122, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27200001	, 'nombre_obgasto' => 'PRENDAS DE PROTECCIÓN', 'obgasto_padre' => 	125, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27300000	, 'nombre_obgasto' => 'ARTÍCULOS DEPORTIVOS', 'obgasto_padre' => 	122, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27300001	, 'nombre_obgasto' => 'ARTÍCULOS DEPORTIVOS', 'obgasto_padre' => 	127, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27400000	, 'nombre_obgasto' => 'PRODUCTOS TEXTILES', 'obgasto_padre' => 	122, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27400001	, 'nombre_obgasto' => 'TEXTILES', 'obgasto_padre' => 	129, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27500000	, 'nombre_obgasto' => 'BLANCOS Y OTROS PRODUCTOS TEXTILES, EXCEPTO PRENDAS DE VESTIR', 'obgasto_padre' => 	122, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	27500001	, 'nombre_obgasto' => 'BLANCOS', 'obgasto_padre' => 	131, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29000000	, 'nombre_obgasto' => 'HERRAMIENTAS, REFACCIONES Y ACCESORIOS MENORES', 'obgasto_padre' => 	63, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29100000	, 'nombre_obgasto' => 'HERRAMIENTAS MENORES', 'obgasto_padre' => 	133, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29100001	, 'nombre_obgasto' => 'REFACCIONES, ACCESORIOS Y HERRAMIENTAS', 'obgasto_padre' => 	134, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29400000	, 'nombre_obgasto' => 'REFACCIONES Y ACCESORIOS MENORES DE EQUIPO DE CÓMPUTO Y TECNOLOGÍAS DE LA INFORMACIÓN', 'obgasto_padre' => 	133, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29400001	, 'nombre_obgasto' => 'REFACCIONES Y ACCESORIOS DE EQUIPO DE CÓMPUTO', 'obgasto_padre' => 	136, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29500000	, 'nombre_obgasto' => 'REFACCIONESYACCESORIOSMENORESDEEQUIPOE INSTRUMENTAL MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	133, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29600000	, 'nombre_obgasto' => 'REFACCIONESYACCESORIOSMENORES DEEQUIPODE TRANSPORTE', 'obgasto_padre' => 	133, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29600001	, 'nombre_obgasto' => 'NEUMÁTICOS Y CÁMARAS', 'obgasto_padre' => 	139, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29900000	, 'nombre_obgasto' => 'REFACCIONES Y ACCESORIOS MENORES OTROS BIENES MUEBLES', 'obgasto_padre' => 	133, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	29900001	, 'nombre_obgasto' => 'MATERIALES Y SUMINISTROS VARIOS', 'obgasto_padre' => 	141, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	30000000	, 'nombre_obgasto' => 'SERVICIOS GENERALES', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31000000	, 'nombre_obgasto' => 'SERVICIOS BÁSICOS', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31100000	, 'nombre_obgasto' => 'ENERGÍA ELÉCTRICA', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31100001	, 'nombre_obgasto' => 'SERVICIO DE ENERGÍA ELÉCTRICA', 'obgasto_padre' => 	145, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31300000	, 'nombre_obgasto' => 'AGUA', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31300001	, 'nombre_obgasto' => 'SERVICIO DE AGUA POTABLE', 'obgasto_padre' => 	147, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31400000	, 'nombre_obgasto' => 'TELEFONÍA TRADICIONAL', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31400001	, 'nombre_obgasto' => 'SERVICIO TELEFÓNICO CONVENCIONAL', 'obgasto_padre' => 	149, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31500000	, 'nombre_obgasto' => 'TELEFONÍA CELULAR', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31500001	, 'nombre_obgasto' => 'SERVICIO DE TELEFONÍA CELULAR', 'obgasto_padre' => 	151, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31700000	, 'nombre_obgasto' => 'SERVICIOS DE ACCESO DE INTERNET, REDES Y PROCESAMIENTO DE INFORMACIÓN', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31700001	, 'nombre_obgasto' => 'SERVICIOS DE CONDUCCIÓN DE SEÑALES ANALÓGICAS Y DIGITALES', 'obgasto_padre' => 	153, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31800000	, 'nombre_obgasto' => 'SERVICIOS POSTALES Y TELEGRÁFICOS', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31800001	, 'nombre_obgasto' => 'SERVICIO POSTAL', 'obgasto_padre' => 	155, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31800002	, 'nombre_obgasto' => 'SERVICIO TELEGRÁFICO', 'obgasto_padre' => 	155, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31800003	, 'nombre_obgasto' => 'SERVICIO DE MENSAJERÍA', 'obgasto_padre' => 	155, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31900000	, 'nombre_obgasto' => 'SERVICIOS INTEGRALES Y OTROS SERVICIOS', 'obgasto_padre' => 	144, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	31900001	, 'nombre_obgasto' => 'CONTRATACIÓN DE OTROS SERVICIOS', 'obgasto_padre' => 	159, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32000000	, 'nombre_obgasto' => 'SERVICIOS DE ARRENDAMIENTO', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32200000	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EDIFICIOS', 'obgasto_padre' => 	161, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32200001	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EDIFICIOS Y LOCALES', 'obgasto_padre' => 	162, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32300000	, 'nombre_obgasto' => 'ARRENDAMIENTO DE MOBILIARIO Y EQUIPO DE ADMINISTRACIÓN, EDUCACIONAL Y RECREATIVO', 'obgasto_padre' => 	161, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32300001	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EQUIPO Y BIENES INFORMÁTICOS', 'obgasto_padre' => 	164, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32300002	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EQUIPO DE FOTOCOPIADO', 'obgasto_padre' => 	164, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32500000	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EQUIPO DE TRANSPORTE', 'obgasto_padre' => 	161, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32500002	, 'nombre_obgasto' => 'ARRENDAMIENTO DE EQUIPO DE TRANSPORTE PARA SERVICIOS Y OPERACIÓN DE PROGRAMAS PÚBLICOS', 'obgasto_padre' => 	167, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32900000	, 'nombre_obgasto' => 'OTROS ARRENDAMIENTOS', 'obgasto_padre' => 	161, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32900001	, 'nombre_obgasto' => 'OTROS ARRENDAMIENTOS', 'obgasto_padre' => 	169, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	32900002	, 'nombre_obgasto' => 'ARRENDAMIENTO DE SERVICIOS DE LIMPIEZA', 'obgasto_padre' => 	169, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33000000	, 'nombre_obgasto' => 'SERVICIOS PROFESIONALES, CIENTÍFICOS, TÉCNICOS Y OTROS SERVICIOS', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33100000	, 'nombre_obgasto' => 'SERVICIOS DE LEGALES, DE CONTABILIDAD, AUDITORÍA Y RELACIONADOS', 'obgasto_padre' => 	172, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33100001	, 'nombre_obgasto' => 'ASESORÍAS ASOCIADAS A CONVENIOS O ACUERDOS', 'obgasto_padre' => 	173, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33300000	, 'nombre_obgasto' => 'SERVICIOS DE CONSULTORÍA ADMINISTRATIVA, PROCESOS, TÉCNICA Y EN TECNOLOGÍAS DE LA INFORMACIÓN', 'obgasto_padre' => 	172, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33300001	, 'nombre_obgasto' => 'SERVICIOS DE INFORMÁTICA', 'obgasto_padre' => 	175, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33400000	, 'nombre_obgasto' => 'SERVICIOS DE CAPACITACIÓN', 'obgasto_padre' => 	172, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33400001	, 'nombre_obgasto' => 'CAPACITACIÓN', 'obgasto_padre' => 	177, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33800000	, 'nombre_obgasto' => 'SERVICIOS DE VIGILANCIA', 'obgasto_padre' => 	172, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33800001	, 'nombre_obgasto' => 'SERVICIOS DE VIGILANCIA', 'obgasto_padre' => 	179, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33900000	, 'nombre_obgasto' => 'SERVICIOS PROFESIONALES, CIENTÍFICOS Y TÉCNICOS INTEGRALES', 'obgasto_padre' => 	172, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33900001	, 'nombre_obgasto' => 'ESTUDIOS, INVESTIGACIONES Y PROYECTOS', 'obgasto_padre' => 	181, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	33900002	, 'nombre_obgasto' => 'SERVICIOS HOSPITALARIOS A DETENIDOS', 'obgasto_padre' => 	181, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34000000	, 'nombre_obgasto' => 'SERVICIOS FINANCIEROS, BANCARIOS Y COMERCIALES', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34100000	, 'nombre_obgasto' => 'SERVICIOS FINANCIEROS Y BANCARIOS', 'obgasto_padre' => 	184, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34100001	, 'nombre_obgasto' => 'SERVICIOS BANCARIOS Y FINANCIEROS', 'obgasto_padre' => 	185, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34500000	, 'nombre_obgasto' => 'SEGURO DE BIENES PATRIMONIALES', 'obgasto_padre' => 	184, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34500001	, 'nombre_obgasto' => 'SEGUROS DE BIENES PATRIMONIALES', 'obgasto_padre' => 	187, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34700000	, 'nombre_obgasto' => 'FLETES Y MANIOBRAS', 'obgasto_padre' => 	184, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	34700001	, 'nombre_obgasto' => 'FLETES Y MANIOBRAS', 'obgasto_padre' => 	189, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35000000	, 'nombre_obgasto' => 'SERVICIOS DE INSTALACIÓN, REPARACIÓN, MANTENIMIENTO Y CONSERVACIÓN', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35100000	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO MENOR DE INMUEBLES', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35100001	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO DE INMUEBLES (EDIFICIOS PÚBLICOS)', 'obgasto_padre' => 	192, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35200000	, 'nombre_obgasto' => 'INSTALACIÓN, REPARACIÓN Y MANTENIMIENTO DE MOBILIARIO Y EQUIPO DE ADMINISTRACIÓN, EDUCACIONAL Y RECREATIVO', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35200001	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO DE EQUIPO Y MOBILIARIO DE ADMINISTRACIÓN', 'obgasto_padre' => 	194, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35200002	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO DE OTROS', 'obgasto_padre' => 	194, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35300000	, 'nombre_obgasto' => 'INSTALACIÓN, REPARACIÓN Y MANTENIMIENTODE EQUIPO DE CÓMPUTO Y TECNOLOGÍA DE LA INFORMACIÓN', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35300001	, 'nombre_obgasto' => 'CONSERVACIÓNYMANTENIMIENTODEBIENES INFORMÁTICOS', 'obgasto_padre' => 	197, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35500000	, 'nombre_obgasto' => 'REPARACIÓN Y MANTENIMIENTO DE EQUIPO DE TRANSPORTE', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35500002	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO DE VEHÍCULOS ADSCRITOS A SERVICIOS Y OPERACIÓN DE PROGRAMAS PÚBLICOS', 'obgasto_padre' => 	199, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35500003	, 'nombre_obgasto' => 'CONSERVACIÓN Y MANTENIMIENTO DE VEHÍCULOS ADSCRITOS A SERVICIOS ADMINISTRATIVOS', 'obgasto_padre' => 	199, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35800000	, 'nombre_obgasto' => 'SERVICIOS DE LIMPIEZA Y MANEJO DE DESECHOS', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35800001	, 'nombre_obgasto' => 'SERVICIO DE LAVANDERÍA, LIMPIEZA, HIGIENE', 'obgasto_padre' => 	202, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35900000	, 'nombre_obgasto' => 'SERVICIOS DE JARDINERÍA Y FUMIGACIÓN', 'obgasto_padre' => 	191, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	35900001	, 'nombre_obgasto' => 'FUMIGACIÓN', 'obgasto_padre' => 	204, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36000000	, 'nombre_obgasto' => 'SERVICIOS DE COMUNICACIÓN SOCIAL Y PUBLICIDAD', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36100000	, 'nombre_obgasto' => 'DIFUSIÓN POR RADIO TELEVISIÓN Y OTROS MEDIOS DE MENSAJES SOBRE PROGRAMAS Y ACTIVIDADES GUBERNAMENTALES', 'obgasto_padre' => 	206, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36100001	, 'nombre_obgasto' => 'PUBLICACIONES OFICIALES PARA DIFUSIÓN E INFORMACIÓN', 'obgasto_padre' => 	207, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36100002	, 'nombre_obgasto' => 'PUBLICACIONES OFICIALES PARA LICITACIONES PÚBLICAS Y TRÁMITES ADMINISTRATIVOS', 'obgasto_padre' => 	207, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36100003	, 'nombre_obgasto' => 'OTROS GASTOS DE PUBLICACIÓN, DIFUSIÓN E INFORMACIÓN', 'obgasto_padre' => 	207, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36100004	, 'nombre_obgasto' => 'IMPRESIONES', 'obgasto_padre' => 	207, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36400000	, 'nombre_obgasto' => 'SERVICIOS DE REVELADO DE FOTOGRAFÍAS', 'obgasto_padre' => 	206, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36400001	, 'nombre_obgasto' => 'SERVICIOS DE REVELADO DE FOTOGRAFÍAS', 'obgasto_padre' => 	212, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36600000	, 'nombre_obgasto' => 'SERVICIO DE CREACIÓN Y DIFUSIÓN DE CONTENIDO EXCLUSIVAMENTE A TRAVÉS DE INTERNET', 'obgasto_padre' => 	206, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36600001	, 'nombre_obgasto' => 'SERVICIO DE CREACIÓN Y DIFUSIÓN DE CONTENIDO EXCLUSIVAMENTE A TRAVÉS DE INTERNET', 'obgasto_padre' => 	214, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	36900000	, 'nombre_obgasto' => 'OTROS SERVICIOS DE INFORMACIÓN', 'obgasto_padre' => 	206, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37000000	, 'nombre_obgasto' => 'SERVICIOS DE TRASLADOS Y VIÁTICOS', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37100000	, 'nombre_obgasto' => 'PASAJES AÉREOS', 'obgasto_padre' => 	217, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37100001	, 'nombre_obgasto' => 'PASAJES NACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	218, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37100002	, 'nombre_obgasto' => 'PASAJES INTERNACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	218, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37200000	, 'nombre_obgasto' => 'PASAJES TERRESTRES', 'obgasto_padre' => 	217, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37200001	, 'nombre_obgasto' => 'PASAJES NACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	221, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37200002	, 'nombre_obgasto' => 'PASAJES INTERNACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	221, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37500000	, 'nombre_obgasto' => 'VIÁTICOS EN EL PAÍS', 'obgasto_padre' => 	217, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37500001	, 'nombre_obgasto' => 'VIÁTICOS NACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	224, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37600000	, 'nombre_obgasto' => 'VIÁTICOS EN EL EXTRANJERO', 'obgasto_padre' => 	217, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37600001	, 'nombre_obgasto' => 'VIÁTICOS INTERNACIONALES A SERVIDORES PÚBLICOS', 'obgasto_padre' => 	226, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37900000	, 'nombre_obgasto' => 'OTROS SERVICIOS DE TRASLADO Y HOSPEDAJE', 'obgasto_padre' => 	217, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37900001	, 'nombre_obgasto' => 'TRASLADOS LOCALES', 'obgasto_padre' => 	228, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37900002	, 'nombre_obgasto' => 'HOSPEDAJES EXTRAORDINARIOS', 'obgasto_padre' => 	228, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37900003	, 'nombre_obgasto' => 'ALIMENTACIÓN EXTRAORDINARIA', 'obgasto_padre' => 	228, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	37900004	, 'nombre_obgasto' => 'TRASLADOS EXTRAORDINARIOS', 'obgasto_padre' => 	228, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38000000	, 'nombre_obgasto' => 'SERVICIOS OFICIALES', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38200000	, 'nombre_obgasto' => 'GASTOS DE ORDEN SOCIAL Y CULTURAL', 'obgasto_padre' => 	233, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38200002	, 'nombre_obgasto' => 'ACTIVIDADES CÍVICAS Y FESTIVIDADES', 'obgasto_padre' => 	234, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38300000	, 'nombre_obgasto' => 'CONGRESOS Y CONVENCIONES', 'obgasto_padre' => 	233, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38300001	, 'nombre_obgasto' => 'CONGRESOS Y CONVENCIONES', 'obgasto_padre' => 	236, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38400000	, 'nombre_obgasto' => 'EXPOSICIONES', 'obgasto_padre' => 	233, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	38400001	, 'nombre_obgasto' => 'EXPOSICIONES', 'obgasto_padre' => 	238, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39000000	, 'nombre_obgasto' => 'OTROS SERVICIOS GENERALES', 'obgasto_padre' => 	143, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39100000	, 'nombre_obgasto' => 'SERVICIOS FUNERARIOS Y DE CEMENTERIOS', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39100001	, 'nombre_obgasto' => 'SERVICIOS FUNERARIOS Y DE CEMENTERIOS', 'obgasto_padre' => 	241, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39200000	, 'nombre_obgasto' => 'IMPUESTOS Y DERECHOS', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39200001	, 'nombre_obgasto' => 'OTROS IMPUESTOS, DERECHOS Y CUOTAS', 'obgasto_padre' => 	243, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39400000	, 'nombre_obgasto' => 'SENTENCIAS Y RESOLUCIONES POR AUTORIDAD COMPETENTE', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39400001	, 'nombre_obgasto' => 'SENTENCIAS Y RESOLUCIONES POR AUTORIDAD COMPETENTE', 'obgasto_padre' => 	245, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39500000	, 'nombre_obgasto' => 'PENAS, MULTAS, ACCESORIOS Y ACTUALIZACIONES', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39500001	, 'nombre_obgasto' => 'PENAS, MULTAS, ACCESORIOS Y ACTUALIZACIONES', 'obgasto_padre' => 	247, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39600000	, 'nombre_obgasto' => 'OTROS GASTOS POR RESPONSABILIDADES', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39600001	, 'nombre_obgasto' => 'OTROS GASTOS POR RESPONSABILIDADES', 'obgasto_padre' => 	249, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39800000	, 'nombre_obgasto' => 'IMPUESTO SOBRE NÓMINAS', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39800001	, 'nombre_obgasto' => 'IMPUESTO 3% SOBRE NÓMINAS', 'obgasto_padre' => 	251, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39800002	, 'nombre_obgasto' => 'IMPUESTO 15% FOMENTO A LA EDUCACIÓN', 'obgasto_padre' => 	251, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39900000	, 'nombre_obgasto' => 'OTROS SERVICIOS GENERALES', 'obgasto_padre' => 	240, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	39900001	, 'nombre_obgasto' => 'FONDO REVOLVENTE', 'obgasto_padre' => 	254, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	40000000	, 'nombre_obgasto' => 'TRANSFERENCIAS, ASIGNACIONES, SUBSIDIOS Y OTRAS AYUDAS', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	44000000	, 'nombre_obgasto' => 'AYUDAS SOCIALES', 'obgasto_padre' => 	256, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	44200000	, 'nombre_obgasto' => 'BECAS Y OTRAS AYUDAS PARA PROGRAMAS DE CAPACITACIÓN', 'obgasto_padre' => 	257, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	44200001	, 'nombre_obgasto' => 'BECAS', 'obgasto_padre' => 	258, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	44500000	, 'nombre_obgasto' => 'AYUDAS SOCIALES A INSTITUCIONES SIN FINES DE LUCRO', 'obgasto_padre' => 	257, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	44500001	, 'nombre_obgasto' => 'SUBSIDIOS A INSTITUCIONES', 'obgasto_padre' => 	260, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	50000000	, 'nombre_obgasto' => 'BIENES MUEBLES, INMUEBLES E INTAGIBLES', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51000000	, 'nombre_obgasto' => 'MOBILIARIO Y EQUIPO DE ADMINISTRACIÓN', 'obgasto_padre' => 	262, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51100000	, 'nombre_obgasto' => 'MUEBLES DE OFICINA Y ESTANTERÍA', 'obgasto_padre' => 	263, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51100001	, 'nombre_obgasto' => 'MOBILIARIO Y EQUIPO DE OFICINA', 'obgasto_padre' => 	264, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51200000	, 'nombre_obgasto' => 'MUEBLES, EXCEPTO DE OFICINA Y ESTANTERÍA', 'obgasto_padre' => 	263, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51200001	, 'nombre_obgasto' => 'OTROS MUEBLES', 'obgasto_padre' => 	266, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51500000	, 'nombre_obgasto' => 'EQUIPO DE CÓMPUTO Y DE TECNOLOGÍAS DE LA INFORMACIÓN', 'obgasto_padre' => 	263, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51500001	, 'nombre_obgasto' => 'BIENES INFORMÁTICOS', 'obgasto_padre' => 	268, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	51900000	, 'nombre_obgasto' => 'OTROS MOBILIARIOS Y EQUIPO DE ADMINISTRACIÓN', 'obgasto_padre' => 	263, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	52000000	, 'nombre_obgasto' => 'MOBILIARIO Y EQUIPO EDUCACIONAL Y RECREATIVO', 'obgasto_padre' => 	262, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	52100000	, 'nombre_obgasto' => 'EQUIPOS Y APARATOS AUDIOVISUALES', 'obgasto_padre' => 	271, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	52100001	, 'nombre_obgasto' => 'EQUIPO AUDIOVISUAL', 'obgasto_padre' => 	272, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	52300000	, 'nombre_obgasto' => 'CÁMARAS FOTOGRÁFICAS Y DE VIDEO', 'obgasto_padre' => 	271, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	52300001	, 'nombre_obgasto' => 'EQUIPO FOTOGRÁFICO', 'obgasto_padre' => 	274, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	53000000	, 'nombre_obgasto' => 'EQUIPO E INSTRUMENTAL MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	262, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	53100000	, 'nombre_obgasto' => 'EQUIPO MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	276, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	53100001	, 'nombre_obgasto' => 'EQUIPO MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	277, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	53200000	, 'nombre_obgasto' => 'INSTRUMENTAL MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	276, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	53200001	, 'nombre_obgasto' => 'INSTRUMENTAL MÉDICO Y DE LABORATORIO', 'obgasto_padre' => 	279, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	54000000	, 'nombre_obgasto' => 'VEHÍCULOS Y EQUIPO DE TRANSPORTE', 'obgasto_padre' => 	262, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	54100000	, 'nombre_obgasto' => 'VEHÍCULOS Y EQUIPO TERRESTRE', 'obgasto_padre' => 	281, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	54100001	, 'nombre_obgasto' => 'VEHÍCULOSTERRESTRESPARAPROGRAMASDE SEGURIDAD PÚBLICA', 'obgasto_padre' => 	282, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	54100002	, 'nombre_obgasto' => 'VEHÍCULOS TERRESTRES PARA SERVICIOS Y OPERACIÓN DE PROGRAMAS PÚBLICOS', 'obgasto_padre' => 	282, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	59000000	, 'nombre_obgasto' => 'ACTIVOS INTANGIBLES', 'obgasto_padre' => 	262, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	59100000	, 'nombre_obgasto' => 'SOFTWARE', 'obgasto_padre' => 	285, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	59100001	, 'nombre_obgasto' => 'SOFTWARE', 'obgasto_padre' => 	286, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	59700000	, 'nombre_obgasto' => 'LICENCIAS INFORMÁTICAS E INTELECTUALES', 'obgasto_padre' => 	285, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	59700001	, 'nombre_obgasto' => 'LICENCIAS INFORMÁTICAS E INTELECTUALES', 'obgasto_padre' => 	288, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	60000000	, 'nombre_obgasto' => 'INVERSIÓN PÚBLICA', 'obgasto_padre' => 	NULL, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	62000000	, 'nombre_obgasto' => 'OBRA PÚBLICA EN BIENES PROPIOS', 'obgasto_padre' => 	290, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	62200000	, 'nombre_obgasto' => 'EDIFICACIÓN NO HABITACIONAL', 'obgasto_padre' => 	291, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	62200001	, 'nombre_obgasto' => 'OBRASDECONSTRUCCIÓNPARAEDIFICIOSNO HABITACIONALES', 'obgasto_padre' => 	292, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	62700000	, 'nombre_obgasto' => 'INSTALACIONES Y EQUIPAMIENTO EN CONSTRUCCIONES', 'obgasto_padre' => 	291, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	62700001	, 'nombre_obgasto' => 'INSTALACIONES YOBRASDECONSTRUCCIÓN ESPECIALIZADA', 'obgasto_padre' => 	294, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	63000000	, 'nombre_obgasto' => 'PROYECTOS PRODUCTIVOS Y ACCIONES DE FOMENTO', 'obgasto_padre' => 	290, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	63200000	, 'nombre_obgasto' => 'EJECUCIÓN DE PROYECTOS PRODUCTIVOS NO INCLUIDOS EN CONCEPTOS ANTERIORES DE ESTE CAPÍTULO', 'obgasto_padre' => 	296, 'estatus' => true],
     ['id'=>'','codigo_obgasto' =>	63200002	, 'nombre_obgasto' => 'INFRAESTRUCTURA PARA EL DESARROLLO', 'obgasto_padre' => 	297, 'estatus' => true],
  ]);
  }
}
