<?php

use Illuminate\Database\Seeder;

class CentroTrabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('centro_trab')->insert([		


[ 'ordenUno'=>90,'ordenDos'=>23,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA NORTE TUXPAN','idAds'=>187,'adscripcion'=>'TUXPAN DE RODRIGUEZ CANO','zona'=>'NORTE TUXPAN','distrito'=>'SEXTO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>24,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO CORDOBA','idAds'=>46,'adscripcion'=>'CORDOBA','zona'=>'CENTRO CORDOBA','distrito'=>'DECIMO CUARTO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>25,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO XALAPA','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>26,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO VERACRUZ','idAds'=>192,'adscripcion'=>'VERACRUZ','zona'=>'CENTRO VERACRUZ','distrito'=>'DECIMO SEPTIMO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>27,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA SUR COATZACOALCOS','idAds'=>40,'adscripcion'=>'COATZACOALCOS','zona'=>'SUR COATZACOALCOS','distrito'=>'VIGESIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>28,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO COSAMALOAPAN','idAds'=>47,'adscripcion'=>'COSAMALOAPAN','zona'=>'CENTRO COSAMALOAPAN','distrito'=>'DECIMO OCTAVO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>29,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA NORTE TANTOYUCA','idAds'=>155,'adscripcion'=>'TANTOYUCA','zona'=>'NORTE TANTOYUCA','distrito'=>'TERCER DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>30,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA COORDINADORA ESPECIALIZADA EN ASUNTOS INDIGENAS Y DE DERECHOS HUMANOS','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>31,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA VISITADURIA GENERAL','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>32,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA COORDINADORA ESPECIALIZADA EN LA INVESTIGACION DE DELITOS DE VIOLENCIA CONTRA LA FAMILIA, MUJERES, NIÑAS Y NIÑOS, Y TRATA DE PERSONAS','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>33,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA DIRECCION DE LOS SERVICIOS PERICIALES','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>34,'descripcionCT'=>'ENLACE ADMINISTRATIVO DE LOS SERVICIOS PERICIALES EN CORDOBA','idAds'=>46,'adscripcion'=>'CORDOBA','zona'=>'CENTRO CORDOBA','distrito'=>'DECIMO CUARTO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>35,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA UNIDAD ESPECIALIZADA EN COMBATE AL SECUESTRO','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>36,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA UNIDAD ESPECIALIZADA EN COMBATE AL SECUESTRO SEDE CORDOBA','idAds'=>46,'adscripcion'=>'CORDOBA','zona'=>'CENTRO CORDOBA','distrito'=>'DECIMO CUARTO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>37,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA DE INVESTIGACIONES MINISTERIALES','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>38,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA DIRECCION DEL CENTRO DE INFORMACION','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>39,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN EL INSTITUTO DE FORMACION PROFESIONAL','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],
[ 'ordenUno'=>90,'ordenDos'=>40,'descripcionCT'=>'ENLACE ADMINISTRATIVO EN EL CENTRO DE EVALUACION Y CONTROL DE CONFIANZA','idAds'=>89,'adscripcion'=>'XALAPA','zona'=>'CENTRO XALAPA','distrito'=>'DECIMO PRIMERO DISTRITO','clasRNPSP'=>'OTRA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION' ],


	    ]);
    }
}
