<?php

use Illuminate\Database\Seeder;

class CentroTrabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('centro_trab')->insert([		


['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA NORTE TUXPAN','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>16],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO CORDOBA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>14],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO XALAPA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>12],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO VERACRUZ','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>18],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA SUR COATZACOALCOS','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>13],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA CENTRO COSAMALOAPAN','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>15],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA REGIONAL ZONA NORTE TANTOYUCA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>17],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA COORDINADORA ESPECIALIZADA EN ASUNTOS INDIGENAS Y DE DERECHOS HUMANOS','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>19],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA COORDINADORA ESPECIALIZADA EN LA INVESTIGACION DE DELITOS DE VIOLENCIA CONTRA LA FAMILIA, MUJERES, NIÑAS Y NIÑOS, Y TRATA DE PERSONAS','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>21],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA DIRECCION DE LOS SERVICIOS PERICIALES','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>5],
['descripcionCT'=>'ENLACE ADMINISTRATIVO DE LOS SERVICIOS PERICIALES EN CORDOBA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>4],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA UNIDAD ESPECIALIZADA EN COMBATE AL SECUESTRO','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>10],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA UNIDAD ESPECIALIZADA EN COMBATE AL SECUESTRO SEDE CORDOBA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>10],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA FISCALIA DE INVESTIGACIONES MINISTERIALES','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>4],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN LA DIRECCION DEL CENTRO DE INFORMACION','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>2],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN EL INSTITUTO DE FORMACION PROFESIONAL','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>2],
['descripcionCT'=>'ENLACE ADMINISTRATIVO EN EL CENTRO DE EVALUACION Y CONTROL DE CONFIANZA','cTDepende'=>'DIRECCION GENERAL DE ADMINISTRACION','idEst'=>11],


	    ]);
    }
}
